Add view commands for products and clients
AY2122S1-CS2103T-T12-1/tp pull request #72
Opened 2021-10-05 11:01 UTC by benluiwj

haven't integrated fully into address book and no testing done yet

2021-10-05 11:39 UTC, SkyBlaise99 requested changes
some small stuffs needs update then should be ok to merge
also update the switch case in addressbookparser so the app actually run ur code

2021-10-05 11:39 UTC, SkyBlaise99 commented on src/main/java/seedu/address/logic/commands/ViewClientCommand.java
> +                    + "product list.\n"
Change to `Client list`?

2021-10-05 11:39 UTC, SkyBlaise99 commented on src/main/java/seedu/address/logic/commands/ViewProductCommand.java
> +                    + "If no such client exists, nothing will be shown\n"
change to `product`

2021-10-05 11:39 UTC, SkyBlaise99 commented on src/main/java/seedu/address/logic/commands/ViewProductCommand.java
> +    public CommandResult execute(Model model) throws CommandException {
Add newlines pls

2021-10-05 11:39 UTC, SkyBlaise99 commented on src/main/java/seedu/address/model/product/ProductContainsIdPredicate.java
> + * Tests that a {@code Client}'s {@code id} matches the id given.
change to `product`

2021-10-05 12:21 UTC, benluiwj commented on src/main/java/seedu/address/logic/commands/ViewProductCommand.java
> +    public CommandResult execute(Model model) throws CommandException {
check style failed when I new lined but ill include it as a change anyways

2021-10-06 08:08 UTC, SkyBlaise99 commented on src/main/java/seedu/address/logic/commands/ViewProductCommand.java
> +    public CommandResult execute(Model model) throws CommandException {
lol wut and why haha

2021-10-06 08:10 UTC, merged